// <auto-generated />
namespace Ptpn8.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _280120221 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_280120221));
        
        string IMigrationMetadata.Id
        {
            get { return "202201280258366_280120221"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
