// <auto-generated />
namespace Ptpn8.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _270120222 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_270120222));
        
        string IMigrationMetadata.Id
        {
            get { return "202201270806102_270120222"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
